/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ifpr.usuario;

import ifpr.usuario.gerenciar.GerenciarUsuario;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author paulojr
 */
public class UsuarioJIF
        extends javax.swing.JInternalFrame
        implements WindowListener
{

    private UsuarioForm usuarioForm;
    private GerenciarUsuario gerUsuario;
    private UsuarioTableModel usuarioTableModel;
    
    /**
     * Creates new form UsuarioJIF
     */
    public UsuarioJIF(JFrame janelaPai) {
        gerUsuario = new GerenciarUsuario();
        usuarioTableModel =
                new UsuarioTableModel(gerUsuario);
        initComponents();
        usuarioForm =
            new UsuarioForm(janelaPai, true,
                    gerUsuario);
        
        usuarioForm.addWindowListener(this);
        
        editarUsuarioBT.setEnabled(false);
        removerUsuarioBT.setEnabled(false);
        mudarSenhaBT.setEnabled(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        usuarioPainelPrincipal = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nomePesquisaTF = new javax.swing.JTextField();
        pesquisarBT = new javax.swing.JButton();
        limparBT = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        novoUsuarioBT = new javax.swing.JButton();
        editarUsuarioBT = new javax.swing.JButton();
        removerUsuarioBT = new javax.swing.JButton();
        mudarSenhaBT = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        usuariosTable = new javax.swing.JTable();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Gerenciamento de usuários");

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setText("PESQUISA");

        jLabel2.setText("Nome do usuário:");

        pesquisarBT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/search.png"))); // NOI18N
        pesquisarBT.setText("Pesquisar");
        pesquisarBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisarBTActionPerformed(evt);
            }
        });

        limparBT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/eraser.png"))); // NOI18N
        limparBT.setText("Limpar");
        limparBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparBTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(nomePesquisaTF)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pesquisarBT)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(limparBT))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomePesquisaTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pesquisarBT)
                    .addComponent(limparBT))
                .addContainerGap(7, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        novoUsuarioBT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/edit_add.png"))); // NOI18N
        novoUsuarioBT.setText("Novo");
        novoUsuarioBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novoUsuarioBTActionPerformed(evt);
            }
        });

        editarUsuarioBT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/edit.png"))); // NOI18N
        editarUsuarioBT.setText("Editar");
        editarUsuarioBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarUsuarioBTActionPerformed(evt);
            }
        });

        removerUsuarioBT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/edit_remove.png"))); // NOI18N
        removerUsuarioBT.setText("Remover");
        removerUsuarioBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerUsuarioBTActionPerformed(evt);
            }
        });

        mudarSenhaBT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/run.png"))); // NOI18N
        mudarSenhaBT.setText("Mudar Senha");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(novoUsuarioBT)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editarUsuarioBT)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(removerUsuarioBT)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mudarSenhaBT)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(novoUsuarioBT)
                    .addComponent(editarUsuarioBT)
                    .addComponent(removerUsuarioBT)
                    .addComponent(mudarSenhaBT))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        usuariosTable.setModel(usuarioTableModel);
        usuariosTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                usuariosTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(usuariosTable);

        javax.swing.GroupLayout usuarioPainelPrincipalLayout = new javax.swing.GroupLayout(usuarioPainelPrincipal);
        usuarioPainelPrincipal.setLayout(usuarioPainelPrincipalLayout);
        usuarioPainelPrincipalLayout.setHorizontalGroup(
            usuarioPainelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(usuarioPainelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(usuarioPainelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        usuarioPainelPrincipalLayout.setVerticalGroup(
            usuarioPainelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(usuarioPainelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(usuarioPainelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(usuarioPainelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void novoUsuarioBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novoUsuarioBTActionPerformed
        usuarioForm.setVisible(true);
    }//GEN-LAST:event_novoUsuarioBTActionPerformed

    private void removerUsuarioBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerUsuarioBTActionPerformed
        int numLinha = usuariosTable.getSelectedRow();
        if ( numLinha >= 0 )
        {
            int id = (int)usuarioTableModel.
                    getValueAt(numLinha, 0);
            Usuario usuario = gerUsuario.buscarUsuario(id);
            int opcao = JOptionPane.
                showConfirmDialog(this,
                    "Corfirma a exclusão do usuário "
                        + usuario.getNome() + "?",
                    "Confirmação",
                    JOptionPane.YES_NO_OPTION);
            
            if ( opcao == JOptionPane.YES_OPTION )
            {
                gerUsuario.remover(usuario.getId());
                usuarioTableModel.atualizar();
                usuariosTable.repaint();
            }
            
        }
    }//GEN-LAST:event_removerUsuarioBTActionPerformed

    private void editarUsuarioBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarUsuarioBTActionPerformed
        int numLinha = usuariosTable.getSelectedRow();
        if ( numLinha >= 0 )
        {
            int id = (int)usuarioTableModel.
                    getValueAt(numLinha, 0);
            usuarioForm.editar(id);
            usuarioForm.setVisible(true);
        }
    }//GEN-LAST:event_editarUsuarioBTActionPerformed

    private void pesquisarBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisarBTActionPerformed
        String nomePesquisa =
                nomePesquisaTF.getText().trim();

        usuarioTableModel.pesquisar(nomePesquisa);
        usuariosTable.repaint();
    }//GEN-LAST:event_pesquisarBTActionPerformed

    private void limparBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparBTActionPerformed
        nomePesquisaTF.setText("");
        usuarioTableModel.atualizar();
        usuariosTable.repaint();
    }//GEN-LAST:event_limparBTActionPerformed

    private void usuariosTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usuariosTableMouseClicked
        int numLinha = usuariosTable.getSelectedRow();
        if ( numLinha >= 0 )
        {
            editarUsuarioBT.setEnabled(true);
            removerUsuarioBT.setEnabled(true);
            mudarSenhaBT.setEnabled(true);
        }
    }//GEN-LAST:event_usuariosTableMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton editarUsuarioBT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton limparBT;
    private javax.swing.JButton mudarSenhaBT;
    private javax.swing.JTextField nomePesquisaTF;
    private javax.swing.JButton novoUsuarioBT;
    private javax.swing.JButton pesquisarBT;
    private javax.swing.JButton removerUsuarioBT;
    private javax.swing.JPanel usuarioPainelPrincipal;
    private javax.swing.JTable usuariosTable;
    // End of variables declaration//GEN-END:variables

    @Override
    public void windowOpened(WindowEvent e) {
        
    }

    @Override
    public void windowClosing(WindowEvent e) {
        
    }

    @Override
    public void windowClosed(WindowEvent e) {
        usuarioTableModel.atualizar();
        usuariosTable.repaint();
    }

    @Override
    public void windowIconified(WindowEvent e) {
        
    }

    @Override
    public void windowDeiconified(WindowEvent e) {
        
    }

    @Override
    public void windowActivated(WindowEvent e) {
        
    }

    @Override
    public void windowDeactivated(WindowEvent e) {
        
    }
}
