/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package ifpr.usuario;

import ifpr.usuario.gerenciar.GerenciarUsuario;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.text.DateFormatter;

/**
 *
 * @author paulojr
 */
public class UsuarioForm extends javax.swing.JDialog {

    private GerenciarUsuario gerUsuario;
    private Usuario usuario;
    
    /**
     * Creates new form UsuarioForm
     */
    public UsuarioForm(JFrame parent, boolean modal,
            GerenciarUsuario gerUsuario) {
        super(parent, modal);
        initComponents();
        this.gerUsuario = gerUsuario;
        atualizarBT.setVisible(false);
    }
    
    public void editar(int id)
    {
        usuario = gerUsuario.buscarUsuario(id);
        nomeTF.setText(usuario.getNome());
        emailTF.setText(usuario.getEmail());
        
        this.converterLocalDateParaString();
        
        if ( usuario.getSexo() == Sexo.MASCULINO )
        {
            masculinoRB.setSelected(true);
        }
        else
        {
            femininoRB.setSelected(true);
        }
        
        senha1PF.setEnabled(false);
        senha2PF.setEnabled(false);
        
        salvarBT.setVisible(false);
        atualizarBT.setVisible(true);
    }
    
    private void converterLocalDateParaString()
    {
        DateTimeFormatter dtf =
            DateTimeFormatter.ofPattern("dd/MM/yyyy");
        String dtNasc =
            dtf.format(usuario.getDataNascimento());
        dataNascimentoTF.setText(dtNasc);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        generoGroup = new javax.swing.ButtonGroup();
        usurarioFormPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        nomeTF = new javax.swing.JTextField();
        emailTF = new javax.swing.JTextField();
        dataNascimentoTF = new javax.swing.JFormattedTextField();
        masculinoRB = new javax.swing.JRadioButton();
        femininoRB = new javax.swing.JRadioButton();
        senha1PF = new javax.swing.JPasswordField();
        senha2PF = new javax.swing.JPasswordField();
        salvarBT = new javax.swing.JButton();
        cancelarBT = new javax.swing.JButton();
        atualizarBT = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel1.setText("DADOS DO USUÁRIO");

        jLabel2.setText("* Nome:");

        jLabel3.setText("* E-mail:");

        jLabel4.setText("Data de nascimento:");

        jLabel5.setText("Sexo:");

        jLabel6.setText("* Senha:");

        jLabel7.setText("* Confirmação da senha:");

        jLabel8.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel8.setText("* Campos Obrigatório");

        nomeTF.setToolTipText("Digite o nome completo do usuário");

        emailTF.setToolTipText("Digite um e-mail válido");

        try {
            dataNascimentoTF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        dataNascimentoTF.setToolTipText("Digite a data de nascimento");

        generoGroup.add(masculinoRB);
        masculinoRB.setText("Masculino");

        generoGroup.add(femininoRB);
        femininoRB.setText("Feminino");

        senha1PF.setToolTipText("A senha deve possuir no mínimo 6 caracteres com letras e números");

        senha2PF.setToolTipText("Repita a senha para confirmar");

        salvarBT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/filesave.png"))); // NOI18N
        salvarBT.setText("Salvar");
        salvarBT.setToolTipText("Salvar o usuário no sistema");
        salvarBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarBTActionPerformed(evt);
            }
        });

        cancelarBT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/cancel.png"))); // NOI18N
        cancelarBT.setText("Cancelar");
        cancelarBT.setToolTipText("Cancelar a operação");
        cancelarBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarBTActionPerformed(evt);
            }
        });

        atualizarBT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/apply.png"))); // NOI18N
        atualizarBT.setText("Atualizar");
        atualizarBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizarBTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout usurarioFormPanelLayout = new javax.swing.GroupLayout(usurarioFormPanel);
        usurarioFormPanel.setLayout(usurarioFormPanelLayout);
        usurarioFormPanelLayout.setHorizontalGroup(
            usurarioFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(usurarioFormPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(usurarioFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(usurarioFormPanelLayout.createSequentialGroup()
                        .addGroup(usurarioFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nomeTF)
                            .addComponent(emailTF)
                            .addComponent(dataNascimentoTF)
                            .addGroup(usurarioFormPanelLayout.createSequentialGroup()
                                .addGroup(usurarioFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addGroup(usurarioFormPanelLayout.createSequentialGroup()
                                        .addComponent(masculinoRB)
                                        .addGap(18, 18, 18)
                                        .addComponent(femininoRB))
                                    .addComponent(jLabel7))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(senha1PF)
                            .addComponent(senha2PF))
                        .addContainerGap())
                    .addGroup(usurarioFormPanelLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(atualizarBT)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(salvarBT)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cancelarBT)
                        .addGap(13, 13, 13))))
        );
        usurarioFormPanelLayout.setVerticalGroup(
            usurarioFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(usurarioFormPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(11, 11, 11)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nomeTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(emailTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dataNascimentoTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jLabel5)
                .addGap(2, 2, 2)
                .addGroup(usurarioFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(masculinoRB)
                    .addComponent(femininoRB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(senha1PF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(usurarioFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(usurarioFormPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(senha2PF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                        .addComponent(jLabel8))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, usurarioFormPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(usurarioFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(salvarBT)
                            .addComponent(cancelarBT)
                            .addComponent(atualizarBT))
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(usurarioFormPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(usurarioFormPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelarBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarBTActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelarBTActionPerformed

    private void salvarBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarBTActionPerformed
        String nome = nomeTF.getText().trim();
        String email = emailTF.getText().trim();
        String dtNasc = dataNascimentoTF.getText().trim();
        
        DateTimeFormatter dtf =
            DateTimeFormatter.ofPattern("dd/MM/yyyy");
        LocalDate dataNascimento =
            LocalDate.parse(dtNasc, dtf);
        
        String senha1 = senha1PF.getPassword().toString();
        String senha2 = senha2PF.getPassword().toString();
        
        boolean isValido = true;
        
        if ( nome.isEmpty() )
        {
            isValido = false;
            JOptionPane.showMessageDialog(this,
                    "Nome é obrigatório");
        }
        
        if ( nome.length() < 3 )
        {
            isValido = false;
            JOptionPane.showMessageDialog(this,
                    "Nome deve conter pelo menos 3 caracteres");
        }
        
        if ( email.isEmpty() )
        {
            isValido = false;
            JOptionPane.showMessageDialog(this,
                    "E-mail é obrigatório");
        }
        
        
        if ( isValido )
        {
            Usuario usuario = new Usuario();
            usuario.setNome(nome);
            usuario.setEmail(email);
            usuario.setDataNascimento(dataNascimento);

            if ( masculinoRB.isSelected() ) {
                usuario.setSexo(Sexo.MASCULINO);
            }
            else {
                usuario.setSexo(Sexo.FEMININO);
            }
            gerUsuario.salvar(usuario);
            this.limparTela();
            this.dispose();
        }
        
    }//GEN-LAST:event_salvarBTActionPerformed

    private void atualizarBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizarBTActionPerformed
        
        String nome = nomeTF.getText().trim();
        String email = emailTF.getText().trim();
        String dtNasc = dataNascimentoTF.getText().trim();
        
        DateTimeFormatter dtf =
            DateTimeFormatter.ofPattern("dd/MM/yyyy");
        LocalDate dataNascimento =
            LocalDate.parse(dtNasc, dtf);
        
        usuario.setNome(nome);
        usuario.setEmail(email);
        usuario.setDataNascimento(dataNascimento);
        
        if ( masculinoRB.isSelected() ) {
            usuario.setSexo(Sexo.MASCULINO);
        }
        else {
            usuario.setSexo(Sexo.FEMININO);
        }
        
        gerUsuario.atualizar(usuario);
        this.limparTela();
        this.dispose();
        
    }//GEN-LAST:event_atualizarBTActionPerformed

    private void limparTela()
    {
        nomeTF.setText("");
        emailTF.setText("");
        dataNascimentoTF.setText("");
        generoGroup.clearSelection();
        senha1PF.setText("");
        senha2PF.setText("");
        
        senha1PF.setEnabled(true);
        senha2PF.setEnabled(true);
        atualizarBT.setVisible(false);
        salvarBT.setVisible(true);
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton atualizarBT;
    private javax.swing.JButton cancelarBT;
    private javax.swing.JFormattedTextField dataNascimentoTF;
    private javax.swing.JTextField emailTF;
    private javax.swing.JRadioButton femininoRB;
    private javax.swing.ButtonGroup generoGroup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JRadioButton masculinoRB;
    private javax.swing.JTextField nomeTF;
    private javax.swing.JButton salvarBT;
    private javax.swing.JPasswordField senha1PF;
    private javax.swing.JPasswordField senha2PF;
    private javax.swing.JPanel usurarioFormPanel;
    // End of variables declaration//GEN-END:variables
}
